# ----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: AMATA Production Co., Ltd.
contact_note: "<a href='mailto:sales@amataproduction.com'>sales@amataproduction.com</a>"
description: >
  อมตะ โปรดักชั่น รับผลิตและออกแบบเสื้อและสื่อสิ่งพิมพ์ทุกชนิด ทั้ง เสื้อพิมพ์ลาย เสื้อกีฬา หน่วยงาน องค์กร มหาลัย กีฬาสี และงานป้ายโฆษณา ป้ายหาเสียง ราคาถูก ผลิตด่วน ส่งไว สร้างแบรนด์อย่างมืออาชีพ
lang: th
icon: page_logo/metalogo.png

url: https://www.amataproduction.com
baseurl:
last_updated: false
impressum_path:
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: false
  theme_light: flat
  theme_dark: gitdimmed

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
amata_footer: true
search_enabled: false
socials_in_search: true
bib_search: false

max_width: 1400px

# -----------------------------------------------------------------------------
# Search configuration
# -----------------------------------------------------------------------------
search_settings:
  exclude_navigation: true
  exclude_dropdown: false
  exclude_posts: false
  exclude_books: true
  exclude_theme: true
  exclude_socials: false

# -----------------------------------------------------------------------------
# Open Graph & Schema.org
# -----------------------------------------------------------------------------

serve_og_meta: true
serve_schema_org: false
og_image: "/assets/img/page_logo/link_pic.png"

# -----------------------------------------------------------------------------
# BibTeX to CV Sync
# -----------------------------------------------------------------------------
auto_sync_publications: false
auto_sync_backup: false

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: G-2EQL4J4Y97
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:

google_site_verification: zjU4uXnFBn_pJRdMKfzSEpEt7lwfwAGHWpTiHdC53CU
bing_site_verification:

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: AMATA Production
blog_description: "รับผลิตและออกแบบเสื้อผ้า และสิ่งพิมพ์"
permalink: /blog/:year/:title/
lsi: false

pagination:
  enabled: false

related_blog_posts:
  enabled: true
  max_related: 5

# -----------------------------------------------------------------------------
# Newsletter
# -----------------------------------------------------------------------------

newsletter:
  enabled: false
  endpoint:

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  projects:
    output: true
    permalink: /products/:path/
    defaults:
      - scope:
          path: ""
          type: projects
        values:
          layout: page
  english:   
    output: true
    permalink: /english/:path/
    defaults:
      - scope:
          path: ""
          type: english
        values:
          layout: page

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
  - _pages/books.md
  - _pages/dropdown.md
  - _pages/news.md
  - _pages/teaching.md
  - _pages/profiles.md
  - _pages/cv.md
  - _pages/repositories.md
  - _pages/publications.md
  
keep_files:
  - CNAME
  - .nojekyll

# -----------------------------------------------------------------------------
# Plug-ins
# -----------------------------------------------------------------------------

plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-regex-replace
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-terser
  - jekyll-toc

sass:
  style: compressed

# -----------------------------------------------------------------------------
# Jekyll Minifier
# -----------------------------------------------------------------------------

jekyll-minifier:
  compress_javascript: true
  exclude: ["robots.txt", "assets/js/search/*.js"]

# -----------------------------------------------------------------------------
# Terser
# -----------------------------------------------------------------------------

terser:
  compress:
    drop_console: true

# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  posts:
    enabled: [year, tags, categories]
    permalinks:
      year: "/blog/:year/"
      tags: "/blog/:type/:name/"
      categories: "/blog/:type/:name/"

display_tags: ["JavaScript", "Python", "R", "HTML/CSS"]
display_categories: ["data-visualization", "cge-model"]


# -----------------------------------------------------------------------------
# Jekyll Link Attributes
# -----------------------------------------------------------------------------

external_links:
  enabled: false
  rel: external nofollow noopener
  target: _blank
  exclude:

# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
   enabled: true
   widths:
     - 480
     - 800
     - 1200
   input_directories:
     - assets/img/
   input_formats:
     - ".jpg"
     - ".jpeg"
     - ".png"
     - ".tiff"
     - ".gif"
   output_formats:
     webp: "-quality 85"


lazy_loading_images: true

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: true
enable_cronitor_analytics: false
enable_pirsch_analytics: false
enable_openpanel_analytics: false
enable_google_verification: true
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
enable_video_embedding: false

